/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface AutocompleteDropdown {
        /**
          * Value for input placeholder
         */
        "placeholder": string;
        /**
          * Values that the auto-complete textbox should search for
         */
        "suggestionlist": string[];
    }
    interface MyComponent {
        /**
          * The first name
         */
        "first": string;
        /**
          * The last name
         */
        "last": string;
        /**
          * The middle name
         */
        "middle": string;
    }
}
declare global {
    interface HTMLAutocompleteDropdownElement extends Components.AutocompleteDropdown, HTMLStencilElement {
    }
    var HTMLAutocompleteDropdownElement: {
        prototype: HTMLAutocompleteDropdownElement;
        new (): HTMLAutocompleteDropdownElement;
    };
    interface HTMLMyComponentElement extends Components.MyComponent, HTMLStencilElement {
    }
    var HTMLMyComponentElement: {
        prototype: HTMLMyComponentElement;
        new (): HTMLMyComponentElement;
    };
    interface HTMLElementTagNameMap {
        "autocomplete-dropdown": HTMLAutocompleteDropdownElement;
        "my-component": HTMLMyComponentElement;
    }
}
declare namespace LocalJSX {
    interface AutocompleteDropdown {
        /**
          * Value for input placeholder
         */
        "placeholder"?: string;
        /**
          * Values that the auto-complete textbox should search for
         */
        "suggestionlist"?: string[];
    }
    interface MyComponent {
        /**
          * The first name
         */
        "first"?: string;
        /**
          * The last name
         */
        "last"?: string;
        /**
          * The middle name
         */
        "middle"?: string;
    }
    interface IntrinsicElements {
        "autocomplete-dropdown": AutocompleteDropdown;
        "my-component": MyComponent;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "autocomplete-dropdown": LocalJSX.AutocompleteDropdown & JSXBase.HTMLAttributes<HTMLAutocompleteDropdownElement>;
            "my-component": LocalJSX.MyComponent & JSXBase.HTMLAttributes<HTMLMyComponentElement>;
        }
    }
}
