/*
SQLyog Ultimate v10.12 
MySQL - 5.1.50-community : Database - wsdb_prod
*********************************************************************
*/

/*!40101 SET NAMES utf8 */;

/*!40101 SET SQL_MODE=''*/;

/*!40014 SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;
CREATE DATABASE /*!32312 IF NOT EXISTS*/`wsdb_prod` /*!40100 DEFAULT CHARACTER SET latin1 */;

USE `wsdb_prod`;

/*Table structure for table `test_test_value_type` */

DROP TABLE IF EXISTS `test_test_value_type`;

CREATE TABLE `test_test_value_type` (
  `testTestValueTypeId` int(11) unsigned NOT NULL AUTO_INCREMENT,
  `testId` int(11) unsigned NOT NULL,
  `testValueTypeId` int(11) unsigned NOT NULL,
  `sortOrder` int(4) unsigned NOT NULL,
  PRIMARY KEY (`testTestValueTypeId`),
  UNIQUE KEY `testTestValueType` (`testId`,`testValueTypeId`)
) ENGINE=MyISAM AUTO_INCREMENT=254 DEFAULT CHARSET=latin1;

/*Data for the table `test_test_value_type` */

insert  into `test_test_value_type`(`testTestValueTypeId`,`testId`,`testValueTypeId`,`sortOrder`) values (1,1,76,5);
insert  into `test_test_value_type`(`testTestValueTypeId`,`testId`,`testValueTypeId`,`sortOrder`) values (2,1,77,10);
insert  into `test_test_value_type`(`testTestValueTypeId`,`testId`,`testValueTypeId`,`sortOrder`) values (3,1,78,15);
insert  into `test_test_value_type`(`testTestValueTypeId`,`testId`,`testValueTypeId`,`sortOrder`) values (4,1,79,20);
insert  into `test_test_value_type`(`testTestValueTypeId`,`testId`,`testValueTypeId`,`sortOrder`) values (5,1,80,25);
insert  into `test_test_value_type`(`testTestValueTypeId`,`testId`,`testValueTypeId`,`sortOrder`) values (6,1,81,30);
insert  into `test_test_value_type`(`testTestValueTypeId`,`testId`,`testValueTypeId`,`sortOrder`) values (7,1,82,35);
insert  into `test_test_value_type`(`testTestValueTypeId`,`testId`,`testValueTypeId`,`sortOrder`) values (8,1,83,40);
insert  into `test_test_value_type`(`testTestValueTypeId`,`testId`,`testValueTypeId`,`sortOrder`) values (9,1,84,45);
insert  into `test_test_value_type`(`testTestValueTypeId`,`testId`,`testValueTypeId`,`sortOrder`) values (10,1,85,50);
insert  into `test_test_value_type`(`testTestValueTypeId`,`testId`,`testValueTypeId`,`sortOrder`) values (11,1,86,55);
insert  into `test_test_value_type`(`testTestValueTypeId`,`testId`,`testValueTypeId`,`sortOrder`) values (12,1,87,60);
insert  into `test_test_value_type`(`testTestValueTypeId`,`testId`,`testValueTypeId`,`sortOrder`) values (13,1,88,65);
insert  into `test_test_value_type`(`testTestValueTypeId`,`testId`,`testValueTypeId`,`sortOrder`) values (14,1,89,70);
insert  into `test_test_value_type`(`testTestValueTypeId`,`testId`,`testValueTypeId`,`sortOrder`) values (15,1,90,75);
insert  into `test_test_value_type`(`testTestValueTypeId`,`testId`,`testValueTypeId`,`sortOrder`) values (16,1,91,80);
insert  into `test_test_value_type`(`testTestValueTypeId`,`testId`,`testValueTypeId`,`sortOrder`) values (17,1,92,85);
insert  into `test_test_value_type`(`testTestValueTypeId`,`testId`,`testValueTypeId`,`sortOrder`) values (18,1,93,90);
insert  into `test_test_value_type`(`testTestValueTypeId`,`testId`,`testValueTypeId`,`sortOrder`) values (19,1,94,95);
insert  into `test_test_value_type`(`testTestValueTypeId`,`testId`,`testValueTypeId`,`sortOrder`) values (20,1,95,100);
insert  into `test_test_value_type`(`testTestValueTypeId`,`testId`,`testValueTypeId`,`sortOrder`) values (21,1,96,105);
insert  into `test_test_value_type`(`testTestValueTypeId`,`testId`,`testValueTypeId`,`sortOrder`) values (22,1,97,110);
insert  into `test_test_value_type`(`testTestValueTypeId`,`testId`,`testValueTypeId`,`sortOrder`) values (23,1,98,115);
insert  into `test_test_value_type`(`testTestValueTypeId`,`testId`,`testValueTypeId`,`sortOrder`) values (24,1,99,120);
insert  into `test_test_value_type`(`testTestValueTypeId`,`testId`,`testValueTypeId`,`sortOrder`) values (25,1,100,125);
insert  into `test_test_value_type`(`testTestValueTypeId`,`testId`,`testValueTypeId`,`sortOrder`) values (26,1,101,127);
insert  into `test_test_value_type`(`testTestValueTypeId`,`testId`,`testValueTypeId`,`sortOrder`) values (27,1,102,127);
insert  into `test_test_value_type`(`testTestValueTypeId`,`testId`,`testValueTypeId`,`sortOrder`) values (28,1,105,127);
insert  into `test_test_value_type`(`testTestValueTypeId`,`testId`,`testValueTypeId`,`sortOrder`) values (29,1,106,127);
insert  into `test_test_value_type`(`testTestValueTypeId`,`testId`,`testValueTypeId`,`sortOrder`) values (30,1,109,127);
insert  into `test_test_value_type`(`testTestValueTypeId`,`testId`,`testValueTypeId`,`sortOrder`) values (31,1,110,127);
insert  into `test_test_value_type`(`testTestValueTypeId`,`testId`,`testValueTypeId`,`sortOrder`) values (32,2,113,5);
insert  into `test_test_value_type`(`testTestValueTypeId`,`testId`,`testValueTypeId`,`sortOrder`) values (33,2,114,10);
insert  into `test_test_value_type`(`testTestValueTypeId`,`testId`,`testValueTypeId`,`sortOrder`) values (34,2,115,15);
insert  into `test_test_value_type`(`testTestValueTypeId`,`testId`,`testValueTypeId`,`sortOrder`) values (35,2,116,20);
insert  into `test_test_value_type`(`testTestValueTypeId`,`testId`,`testValueTypeId`,`sortOrder`) values (36,3,117,5);
insert  into `test_test_value_type`(`testTestValueTypeId`,`testId`,`testValueTypeId`,`sortOrder`) values (37,3,118,10);
insert  into `test_test_value_type`(`testTestValueTypeId`,`testId`,`testValueTypeId`,`sortOrder`) values (38,3,119,15);
insert  into `test_test_value_type`(`testTestValueTypeId`,`testId`,`testValueTypeId`,`sortOrder`) values (39,3,120,20);
insert  into `test_test_value_type`(`testTestValueTypeId`,`testId`,`testValueTypeId`,`sortOrder`) values (40,4,121,5);
insert  into `test_test_value_type`(`testTestValueTypeId`,`testId`,`testValueTypeId`,`sortOrder`) values (41,4,122,10);
insert  into `test_test_value_type`(`testTestValueTypeId`,`testId`,`testValueTypeId`,`sortOrder`) values (42,4,124,15);
insert  into `test_test_value_type`(`testTestValueTypeId`,`testId`,`testValueTypeId`,`sortOrder`) values (43,4,125,20);
insert  into `test_test_value_type`(`testTestValueTypeId`,`testId`,`testValueTypeId`,`sortOrder`) values (44,4,126,25);
insert  into `test_test_value_type`(`testTestValueTypeId`,`testId`,`testValueTypeId`,`sortOrder`) values (45,4,127,30);
insert  into `test_test_value_type`(`testTestValueTypeId`,`testId`,`testValueTypeId`,`sortOrder`) values (46,5,128,5);
insert  into `test_test_value_type`(`testTestValueTypeId`,`testId`,`testValueTypeId`,`sortOrder`) values (47,5,129,10);
insert  into `test_test_value_type`(`testTestValueTypeId`,`testId`,`testValueTypeId`,`sortOrder`) values (48,5,130,15);
insert  into `test_test_value_type`(`testTestValueTypeId`,`testId`,`testValueTypeId`,`sortOrder`) values (49,5,131,20);
insert  into `test_test_value_type`(`testTestValueTypeId`,`testId`,`testValueTypeId`,`sortOrder`) values (50,5,132,25);
insert  into `test_test_value_type`(`testTestValueTypeId`,`testId`,`testValueTypeId`,`sortOrder`) values (51,5,133,30);
insert  into `test_test_value_type`(`testTestValueTypeId`,`testId`,`testValueTypeId`,`sortOrder`) values (52,5,134,35);
insert  into `test_test_value_type`(`testTestValueTypeId`,`testId`,`testValueTypeId`,`sortOrder`) values (53,5,135,40);
insert  into `test_test_value_type`(`testTestValueTypeId`,`testId`,`testValueTypeId`,`sortOrder`) values (54,5,136,45);
insert  into `test_test_value_type`(`testTestValueTypeId`,`testId`,`testValueTypeId`,`sortOrder`) values (55,5,137,55);
insert  into `test_test_value_type`(`testTestValueTypeId`,`testId`,`testValueTypeId`,`sortOrder`) values (56,5,138,50);
insert  into `test_test_value_type`(`testTestValueTypeId`,`testId`,`testValueTypeId`,`sortOrder`) values (57,5,139,60);
insert  into `test_test_value_type`(`testTestValueTypeId`,`testId`,`testValueTypeId`,`sortOrder`) values (58,5,140,65);
insert  into `test_test_value_type`(`testTestValueTypeId`,`testId`,`testValueTypeId`,`sortOrder`) values (59,5,141,70);
insert  into `test_test_value_type`(`testTestValueTypeId`,`testId`,`testValueTypeId`,`sortOrder`) values (60,5,142,75);
insert  into `test_test_value_type`(`testTestValueTypeId`,`testId`,`testValueTypeId`,`sortOrder`) values (61,5,143,80);
insert  into `test_test_value_type`(`testTestValueTypeId`,`testId`,`testValueTypeId`,`sortOrder`) values (62,5,144,85);
insert  into `test_test_value_type`(`testTestValueTypeId`,`testId`,`testValueTypeId`,`sortOrder`) values (63,5,145,90);
insert  into `test_test_value_type`(`testTestValueTypeId`,`testId`,`testValueTypeId`,`sortOrder`) values (64,5,146,95);
insert  into `test_test_value_type`(`testTestValueTypeId`,`testId`,`testValueTypeId`,`sortOrder`) values (65,5,147,100);
insert  into `test_test_value_type`(`testTestValueTypeId`,`testId`,`testValueTypeId`,`sortOrder`) values (66,5,148,105);
insert  into `test_test_value_type`(`testTestValueTypeId`,`testId`,`testValueTypeId`,`sortOrder`) values (67,5,149,110);
insert  into `test_test_value_type`(`testTestValueTypeId`,`testId`,`testValueTypeId`,`sortOrder`) values (68,5,150,115);
insert  into `test_test_value_type`(`testTestValueTypeId`,`testId`,`testValueTypeId`,`sortOrder`) values (69,5,151,120);
insert  into `test_test_value_type`(`testTestValueTypeId`,`testId`,`testValueTypeId`,`sortOrder`) values (70,5,152,125);
insert  into `test_test_value_type`(`testTestValueTypeId`,`testId`,`testValueTypeId`,`sortOrder`) values (71,5,153,130);
insert  into `test_test_value_type`(`testTestValueTypeId`,`testId`,`testValueTypeId`,`sortOrder`) values (72,5,154,135);
insert  into `test_test_value_type`(`testTestValueTypeId`,`testId`,`testValueTypeId`,`sortOrder`) values (73,5,155,140);
insert  into `test_test_value_type`(`testTestValueTypeId`,`testId`,`testValueTypeId`,`sortOrder`) values (74,5,156,145);
insert  into `test_test_value_type`(`testTestValueTypeId`,`testId`,`testValueTypeId`,`sortOrder`) values (75,5,157,150);
insert  into `test_test_value_type`(`testTestValueTypeId`,`testId`,`testValueTypeId`,`sortOrder`) values (76,5,158,155);
insert  into `test_test_value_type`(`testTestValueTypeId`,`testId`,`testValueTypeId`,`sortOrder`) values (77,5,159,160);
insert  into `test_test_value_type`(`testTestValueTypeId`,`testId`,`testValueTypeId`,`sortOrder`) values (78,5,160,165);
insert  into `test_test_value_type`(`testTestValueTypeId`,`testId`,`testValueTypeId`,`sortOrder`) values (79,5,161,170);
insert  into `test_test_value_type`(`testTestValueTypeId`,`testId`,`testValueTypeId`,`sortOrder`) values (80,5,162,175);
insert  into `test_test_value_type`(`testTestValueTypeId`,`testId`,`testValueTypeId`,`sortOrder`) values (81,5,163,180);
insert  into `test_test_value_type`(`testTestValueTypeId`,`testId`,`testValueTypeId`,`sortOrder`) values (82,5,164,185);
insert  into `test_test_value_type`(`testTestValueTypeId`,`testId`,`testValueTypeId`,`sortOrder`) values (83,5,165,190);
insert  into `test_test_value_type`(`testTestValueTypeId`,`testId`,`testValueTypeId`,`sortOrder`) values (84,5,166,195);
insert  into `test_test_value_type`(`testTestValueTypeId`,`testId`,`testValueTypeId`,`sortOrder`) values (85,6,167,5);
insert  into `test_test_value_type`(`testTestValueTypeId`,`testId`,`testValueTypeId`,`sortOrder`) values (86,6,168,10);
insert  into `test_test_value_type`(`testTestValueTypeId`,`testId`,`testValueTypeId`,`sortOrder`) values (87,6,169,15);
insert  into `test_test_value_type`(`testTestValueTypeId`,`testId`,`testValueTypeId`,`sortOrder`) values (88,6,170,20);
insert  into `test_test_value_type`(`testTestValueTypeId`,`testId`,`testValueTypeId`,`sortOrder`) values (89,6,171,78);
insert  into `test_test_value_type`(`testTestValueTypeId`,`testId`,`testValueTypeId`,`sortOrder`) values (90,6,172,60);
insert  into `test_test_value_type`(`testTestValueTypeId`,`testId`,`testValueTypeId`,`sortOrder`) values (91,6,173,35);
insert  into `test_test_value_type`(`testTestValueTypeId`,`testId`,`testValueTypeId`,`sortOrder`) values (92,6,351,245);
insert  into `test_test_value_type`(`testTestValueTypeId`,`testId`,`testValueTypeId`,`sortOrder`) values (93,6,174,40);
insert  into `test_test_value_type`(`testTestValueTypeId`,`testId`,`testValueTypeId`,`sortOrder`) values (94,6,352,250);
insert  into `test_test_value_type`(`testTestValueTypeId`,`testId`,`testValueTypeId`,`sortOrder`) values (95,6,175,68);
insert  into `test_test_value_type`(`testTestValueTypeId`,`testId`,`testValueTypeId`,`sortOrder`) values (96,6,176,28);
insert  into `test_test_value_type`(`testTestValueTypeId`,`testId`,`testValueTypeId`,`sortOrder`) values (97,6,177,30);
insert  into `test_test_value_type`(`testTestValueTypeId`,`testId`,`testValueTypeId`,`sortOrder`) values (98,6,178,50);
insert  into `test_test_value_type`(`testTestValueTypeId`,`testId`,`testValueTypeId`,`sortOrder`) values (99,6,179,43);
insert  into `test_test_value_type`(`testTestValueTypeId`,`testId`,`testValueTypeId`,`sortOrder`) values (100,6,180,70);
insert  into `test_test_value_type`(`testTestValueTypeId`,`testId`,`testValueTypeId`,`sortOrder`) values (101,6,181,75);
insert  into `test_test_value_type`(`testTestValueTypeId`,`testId`,`testValueTypeId`,`sortOrder`) values (102,6,182,80);
insert  into `test_test_value_type`(`testTestValueTypeId`,`testId`,`testValueTypeId`,`sortOrder`) values (103,6,183,65);
insert  into `test_test_value_type`(`testTestValueTypeId`,`testId`,`testValueTypeId`,`sortOrder`) values (104,6,345,215);
insert  into `test_test_value_type`(`testTestValueTypeId`,`testId`,`testValueTypeId`,`sortOrder`) values (105,6,343,205);
insert  into `test_test_value_type`(`testTestValueTypeId`,`testId`,`testValueTypeId`,`sortOrder`) values (106,6,344,210);
insert  into `test_test_value_type`(`testTestValueTypeId`,`testId`,`testValueTypeId`,`sortOrder`) values (107,6,341,195);
insert  into `test_test_value_type`(`testTestValueTypeId`,`testId`,`testValueTypeId`,`sortOrder`) values (108,6,342,200);
insert  into `test_test_value_type`(`testTestValueTypeId`,`testId`,`testValueTypeId`,`sortOrder`) values (109,6,187,105);
insert  into `test_test_value_type`(`testTestValueTypeId`,`testId`,`testValueTypeId`,`sortOrder`) values (110,6,188,110);
insert  into `test_test_value_type`(`testTestValueTypeId`,`testId`,`testValueTypeId`,`sortOrder`) values (111,6,190,120);
insert  into `test_test_value_type`(`testTestValueTypeId`,`testId`,`testValueTypeId`,`sortOrder`) values (112,6,191,125);
insert  into `test_test_value_type`(`testTestValueTypeId`,`testId`,`testValueTypeId`,`sortOrder`) values (113,6,192,130);
insert  into `test_test_value_type`(`testTestValueTypeId`,`testId`,`testValueTypeId`,`sortOrder`) values (114,6,193,135);
insert  into `test_test_value_type`(`testTestValueTypeId`,`testId`,`testValueTypeId`,`sortOrder`) values (115,6,194,140);
insert  into `test_test_value_type`(`testTestValueTypeId`,`testId`,`testValueTypeId`,`sortOrder`) values (116,6,195,145);
insert  into `test_test_value_type`(`testTestValueTypeId`,`testId`,`testValueTypeId`,`sortOrder`) values (117,6,196,150);
insert  into `test_test_value_type`(`testTestValueTypeId`,`testId`,`testValueTypeId`,`sortOrder`) values (118,6,197,155);
insert  into `test_test_value_type`(`testTestValueTypeId`,`testId`,`testValueTypeId`,`sortOrder`) values (119,6,198,160);
insert  into `test_test_value_type`(`testTestValueTypeId`,`testId`,`testValueTypeId`,`sortOrder`) values (120,6,199,165);
insert  into `test_test_value_type`(`testTestValueTypeId`,`testId`,`testValueTypeId`,`sortOrder`) values (121,6,200,170);
insert  into `test_test_value_type`(`testTestValueTypeId`,`testId`,`testValueTypeId`,`sortOrder`) values (122,6,201,175);
insert  into `test_test_value_type`(`testTestValueTypeId`,`testId`,`testValueTypeId`,`sortOrder`) values (123,6,202,180);
insert  into `test_test_value_type`(`testTestValueTypeId`,`testId`,`testValueTypeId`,`sortOrder`) values (124,7,203,5);
insert  into `test_test_value_type`(`testTestValueTypeId`,`testId`,`testValueTypeId`,`sortOrder`) values (125,7,204,10);
insert  into `test_test_value_type`(`testTestValueTypeId`,`testId`,`testValueTypeId`,`sortOrder`) values (126,7,205,15);
insert  into `test_test_value_type`(`testTestValueTypeId`,`testId`,`testValueTypeId`,`sortOrder`) values (127,7,206,20);
insert  into `test_test_value_type`(`testTestValueTypeId`,`testId`,`testValueTypeId`,`sortOrder`) values (128,7,207,25);
insert  into `test_test_value_type`(`testTestValueTypeId`,`testId`,`testValueTypeId`,`sortOrder`) values (129,7,208,30);
insert  into `test_test_value_type`(`testTestValueTypeId`,`testId`,`testValueTypeId`,`sortOrder`) values (130,7,209,35);
insert  into `test_test_value_type`(`testTestValueTypeId`,`testId`,`testValueTypeId`,`sortOrder`) values (131,7,210,40);
insert  into `test_test_value_type`(`testTestValueTypeId`,`testId`,`testValueTypeId`,`sortOrder`) values (132,7,211,45);
insert  into `test_test_value_type`(`testTestValueTypeId`,`testId`,`testValueTypeId`,`sortOrder`) values (133,7,212,50);
insert  into `test_test_value_type`(`testTestValueTypeId`,`testId`,`testValueTypeId`,`sortOrder`) values (134,7,213,55);
insert  into `test_test_value_type`(`testTestValueTypeId`,`testId`,`testValueTypeId`,`sortOrder`) values (135,7,214,60);
insert  into `test_test_value_type`(`testTestValueTypeId`,`testId`,`testValueTypeId`,`sortOrder`) values (136,7,215,65);
insert  into `test_test_value_type`(`testTestValueTypeId`,`testId`,`testValueTypeId`,`sortOrder`) values (137,7,216,70);
insert  into `test_test_value_type`(`testTestValueTypeId`,`testId`,`testValueTypeId`,`sortOrder`) values (138,7,217,75);
insert  into `test_test_value_type`(`testTestValueTypeId`,`testId`,`testValueTypeId`,`sortOrder`) values (139,7,218,80);
insert  into `test_test_value_type`(`testTestValueTypeId`,`testId`,`testValueTypeId`,`sortOrder`) values (140,7,219,85);
insert  into `test_test_value_type`(`testTestValueTypeId`,`testId`,`testValueTypeId`,`sortOrder`) values (141,7,220,90);
insert  into `test_test_value_type`(`testTestValueTypeId`,`testId`,`testValueTypeId`,`sortOrder`) values (142,7,221,95);
insert  into `test_test_value_type`(`testTestValueTypeId`,`testId`,`testValueTypeId`,`sortOrder`) values (143,7,222,100);
insert  into `test_test_value_type`(`testTestValueTypeId`,`testId`,`testValueTypeId`,`sortOrder`) values (144,7,223,105);
insert  into `test_test_value_type`(`testTestValueTypeId`,`testId`,`testValueTypeId`,`sortOrder`) values (145,7,224,110);
insert  into `test_test_value_type`(`testTestValueTypeId`,`testId`,`testValueTypeId`,`sortOrder`) values (146,7,225,115);
insert  into `test_test_value_type`(`testTestValueTypeId`,`testId`,`testValueTypeId`,`sortOrder`) values (147,7,226,120);
insert  into `test_test_value_type`(`testTestValueTypeId`,`testId`,`testValueTypeId`,`sortOrder`) values (148,7,227,125);
insert  into `test_test_value_type`(`testTestValueTypeId`,`testId`,`testValueTypeId`,`sortOrder`) values (149,7,228,130);
insert  into `test_test_value_type`(`testTestValueTypeId`,`testId`,`testValueTypeId`,`sortOrder`) values (150,7,229,135);
insert  into `test_test_value_type`(`testTestValueTypeId`,`testId`,`testValueTypeId`,`sortOrder`) values (151,7,230,140);
insert  into `test_test_value_type`(`testTestValueTypeId`,`testId`,`testValueTypeId`,`sortOrder`) values (152,7,231,145);
insert  into `test_test_value_type`(`testTestValueTypeId`,`testId`,`testValueTypeId`,`sortOrder`) values (153,7,232,150);
insert  into `test_test_value_type`(`testTestValueTypeId`,`testId`,`testValueTypeId`,`sortOrder`) values (154,7,233,155);
insert  into `test_test_value_type`(`testTestValueTypeId`,`testId`,`testValueTypeId`,`sortOrder`) values (155,7,234,160);
insert  into `test_test_value_type`(`testTestValueTypeId`,`testId`,`testValueTypeId`,`sortOrder`) values (156,7,235,165);
insert  into `test_test_value_type`(`testTestValueTypeId`,`testId`,`testValueTypeId`,`sortOrder`) values (157,7,236,205);
insert  into `test_test_value_type`(`testTestValueTypeId`,`testId`,`testValueTypeId`,`sortOrder`) values (158,7,237,210);
insert  into `test_test_value_type`(`testTestValueTypeId`,`testId`,`testValueTypeId`,`sortOrder`) values (159,7,238,215);
insert  into `test_test_value_type`(`testTestValueTypeId`,`testId`,`testValueTypeId`,`sortOrder`) values (160,7,239,220);
insert  into `test_test_value_type`(`testTestValueTypeId`,`testId`,`testValueTypeId`,`sortOrder`) values (161,8,240,5);
insert  into `test_test_value_type`(`testTestValueTypeId`,`testId`,`testValueTypeId`,`sortOrder`) values (162,8,241,10);
insert  into `test_test_value_type`(`testTestValueTypeId`,`testId`,`testValueTypeId`,`sortOrder`) values (163,8,242,15);
insert  into `test_test_value_type`(`testTestValueTypeId`,`testId`,`testValueTypeId`,`sortOrder`) values (164,8,243,20);
insert  into `test_test_value_type`(`testTestValueTypeId`,`testId`,`testValueTypeId`,`sortOrder`) values (165,8,244,25);
insert  into `test_test_value_type`(`testTestValueTypeId`,`testId`,`testValueTypeId`,`sortOrder`) values (166,8,245,30);
insert  into `test_test_value_type`(`testTestValueTypeId`,`testId`,`testValueTypeId`,`sortOrder`) values (167,9,246,5);
insert  into `test_test_value_type`(`testTestValueTypeId`,`testId`,`testValueTypeId`,`sortOrder`) values (168,9,247,10);
insert  into `test_test_value_type`(`testTestValueTypeId`,`testId`,`testValueTypeId`,`sortOrder`) values (169,9,248,15);
insert  into `test_test_value_type`(`testTestValueTypeId`,`testId`,`testValueTypeId`,`sortOrder`) values (170,9,249,20);
insert  into `test_test_value_type`(`testTestValueTypeId`,`testId`,`testValueTypeId`,`sortOrder`) values (171,9,251,30);
insert  into `test_test_value_type`(`testTestValueTypeId`,`testId`,`testValueTypeId`,`sortOrder`) values (172,9,252,35);
insert  into `test_test_value_type`(`testTestValueTypeId`,`testId`,`testValueTypeId`,`sortOrder`) values (173,9,253,40);
insert  into `test_test_value_type`(`testTestValueTypeId`,`testId`,`testValueTypeId`,`sortOrder`) values (174,9,254,45);
insert  into `test_test_value_type`(`testTestValueTypeId`,`testId`,`testValueTypeId`,`sortOrder`) values (175,9,256,55);
insert  into `test_test_value_type`(`testTestValueTypeId`,`testId`,`testValueTypeId`,`sortOrder`) values (176,9,257,60);
insert  into `test_test_value_type`(`testTestValueTypeId`,`testId`,`testValueTypeId`,`sortOrder`) values (177,9,258,65);
insert  into `test_test_value_type`(`testTestValueTypeId`,`testId`,`testValueTypeId`,`sortOrder`) values (178,9,259,70);
insert  into `test_test_value_type`(`testTestValueTypeId`,`testId`,`testValueTypeId`,`sortOrder`) values (179,9,261,80);
insert  into `test_test_value_type`(`testTestValueTypeId`,`testId`,`testValueTypeId`,`sortOrder`) values (180,9,262,85);
insert  into `test_test_value_type`(`testTestValueTypeId`,`testId`,`testValueTypeId`,`sortOrder`) values (181,9,263,90);
insert  into `test_test_value_type`(`testTestValueTypeId`,`testId`,`testValueTypeId`,`sortOrder`) values (182,9,264,95);
insert  into `test_test_value_type`(`testTestValueTypeId`,`testId`,`testValueTypeId`,`sortOrder`) values (183,9,266,105);
insert  into `test_test_value_type`(`testTestValueTypeId`,`testId`,`testValueTypeId`,`sortOrder`) values (184,9,267,110);
insert  into `test_test_value_type`(`testTestValueTypeId`,`testId`,`testValueTypeId`,`sortOrder`) values (185,9,268,115);
insert  into `test_test_value_type`(`testTestValueTypeId`,`testId`,`testValueTypeId`,`sortOrder`) values (186,9,269,120);
insert  into `test_test_value_type`(`testTestValueTypeId`,`testId`,`testValueTypeId`,`sortOrder`) values (187,9,271,130);
insert  into `test_test_value_type`(`testTestValueTypeId`,`testId`,`testValueTypeId`,`sortOrder`) values (188,9,272,135);
insert  into `test_test_value_type`(`testTestValueTypeId`,`testId`,`testValueTypeId`,`sortOrder`) values (189,9,273,140);
insert  into `test_test_value_type`(`testTestValueTypeId`,`testId`,`testValueTypeId`,`sortOrder`) values (190,9,274,145);
insert  into `test_test_value_type`(`testTestValueTypeId`,`testId`,`testValueTypeId`,`sortOrder`) values (191,9,276,155);
insert  into `test_test_value_type`(`testTestValueTypeId`,`testId`,`testValueTypeId`,`sortOrder`) values (192,9,277,160);
insert  into `test_test_value_type`(`testTestValueTypeId`,`testId`,`testValueTypeId`,`sortOrder`) values (193,9,278,165);
insert  into `test_test_value_type`(`testTestValueTypeId`,`testId`,`testValueTypeId`,`sortOrder`) values (194,9,279,170);
insert  into `test_test_value_type`(`testTestValueTypeId`,`testId`,`testValueTypeId`,`sortOrder`) values (195,9,281,180);
insert  into `test_test_value_type`(`testTestValueTypeId`,`testId`,`testValueTypeId`,`sortOrder`) values (196,9,282,185);
insert  into `test_test_value_type`(`testTestValueTypeId`,`testId`,`testValueTypeId`,`sortOrder`) values (197,9,283,190);
insert  into `test_test_value_type`(`testTestValueTypeId`,`testId`,`testValueTypeId`,`sortOrder`) values (198,9,284,195);
insert  into `test_test_value_type`(`testTestValueTypeId`,`testId`,`testValueTypeId`,`sortOrder`) values (199,9,286,205);
insert  into `test_test_value_type`(`testTestValueTypeId`,`testId`,`testValueTypeId`,`sortOrder`) values (200,9,287,210);
insert  into `test_test_value_type`(`testTestValueTypeId`,`testId`,`testValueTypeId`,`sortOrder`) values (201,9,288,215);
insert  into `test_test_value_type`(`testTestValueTypeId`,`testId`,`testValueTypeId`,`sortOrder`) values (202,9,289,220);
insert  into `test_test_value_type`(`testTestValueTypeId`,`testId`,`testValueTypeId`,`sortOrder`) values (203,9,291,230);
insert  into `test_test_value_type`(`testTestValueTypeId`,`testId`,`testValueTypeId`,`sortOrder`) values (204,9,292,235);
insert  into `test_test_value_type`(`testTestValueTypeId`,`testId`,`testValueTypeId`,`sortOrder`) values (205,9,293,240);
insert  into `test_test_value_type`(`testTestValueTypeId`,`testId`,`testValueTypeId`,`sortOrder`) values (206,9,294,245);
insert  into `test_test_value_type`(`testTestValueTypeId`,`testId`,`testValueTypeId`,`sortOrder`) values (207,9,296,230);
insert  into `test_test_value_type`(`testTestValueTypeId`,`testId`,`testValueTypeId`,`sortOrder`) values (208,9,297,235);
insert  into `test_test_value_type`(`testTestValueTypeId`,`testId`,`testValueTypeId`,`sortOrder`) values (209,9,298,240);
insert  into `test_test_value_type`(`testTestValueTypeId`,`testId`,`testValueTypeId`,`sortOrder`) values (210,9,299,245);
insert  into `test_test_value_type`(`testTestValueTypeId`,`testId`,`testValueTypeId`,`sortOrder`) values (211,9,301,255);
insert  into `test_test_value_type`(`testTestValueTypeId`,`testId`,`testValueTypeId`,`sortOrder`) values (212,9,302,260);
insert  into `test_test_value_type`(`testTestValueTypeId`,`testId`,`testValueTypeId`,`sortOrder`) values (213,9,303,265);
insert  into `test_test_value_type`(`testTestValueTypeId`,`testId`,`testValueTypeId`,`sortOrder`) values (214,9,304,270);
insert  into `test_test_value_type`(`testTestValueTypeId`,`testId`,`testValueTypeId`,`sortOrder`) values (215,9,306,280);
insert  into `test_test_value_type`(`testTestValueTypeId`,`testId`,`testValueTypeId`,`sortOrder`) values (216,9,307,285);
insert  into `test_test_value_type`(`testTestValueTypeId`,`testId`,`testValueTypeId`,`sortOrder`) values (217,9,308,290);
insert  into `test_test_value_type`(`testTestValueTypeId`,`testId`,`testValueTypeId`,`sortOrder`) values (218,9,309,295);
insert  into `test_test_value_type`(`testTestValueTypeId`,`testId`,`testValueTypeId`,`sortOrder`) values (219,9,311,305);
insert  into `test_test_value_type`(`testTestValueTypeId`,`testId`,`testValueTypeId`,`sortOrder`) values (220,9,312,310);
insert  into `test_test_value_type`(`testTestValueTypeId`,`testId`,`testValueTypeId`,`sortOrder`) values (221,9,313,315);
insert  into `test_test_value_type`(`testTestValueTypeId`,`testId`,`testValueTypeId`,`sortOrder`) values (222,9,314,320);
insert  into `test_test_value_type`(`testTestValueTypeId`,`testId`,`testValueTypeId`,`sortOrder`) values (223,9,316,330);
insert  into `test_test_value_type`(`testTestValueTypeId`,`testId`,`testValueTypeId`,`sortOrder`) values (224,9,317,335);
insert  into `test_test_value_type`(`testTestValueTypeId`,`testId`,`testValueTypeId`,`sortOrder`) values (225,9,318,340);
insert  into `test_test_value_type`(`testTestValueTypeId`,`testId`,`testValueTypeId`,`sortOrder`) values (226,9,319,345);
insert  into `test_test_value_type`(`testTestValueTypeId`,`testId`,`testValueTypeId`,`sortOrder`) values (227,6,349,235);
insert  into `test_test_value_type`(`testTestValueTypeId`,`testId`,`testValueTypeId`,`sortOrder`) values (228,6,350,240);
insert  into `test_test_value_type`(`testTestValueTypeId`,`testId`,`testValueTypeId`,`sortOrder`) values (229,9,321,355);
insert  into `test_test_value_type`(`testTestValueTypeId`,`testId`,`testValueTypeId`,`sortOrder`) values (230,9,322,360);
insert  into `test_test_value_type`(`testTestValueTypeId`,`testId`,`testValueTypeId`,`sortOrder`) values (231,9,323,365);
insert  into `test_test_value_type`(`testTestValueTypeId`,`testId`,`testValueTypeId`,`sortOrder`) values (232,6,354,215);
insert  into `test_test_value_type`(`testTestValueTypeId`,`testId`,`testValueTypeId`,`sortOrder`) values (233,9,324,370);
insert  into `test_test_value_type`(`testTestValueTypeId`,`testId`,`testValueTypeId`,`sortOrder`) values (234,6,348,230);
insert  into `test_test_value_type`(`testTestValueTypeId`,`testId`,`testValueTypeId`,`sortOrder`) values (235,9,326,380);
insert  into `test_test_value_type`(`testTestValueTypeId`,`testId`,`testValueTypeId`,`sortOrder`) values (236,6,353,255);
insert  into `test_test_value_type`(`testTestValueTypeId`,`testId`,`testValueTypeId`,`sortOrder`) values (237,9,327,385);
insert  into `test_test_value_type`(`testTestValueTypeId`,`testId`,`testValueTypeId`,`sortOrder`) values (238,9,328,390);
insert  into `test_test_value_type`(`testTestValueTypeId`,`testId`,`testValueTypeId`,`sortOrder`) values (239,9,329,395);
insert  into `test_test_value_type`(`testTestValueTypeId`,`testId`,`testValueTypeId`,`sortOrder`) values (240,6,347,225);
insert  into `test_test_value_type`(`testTestValueTypeId`,`testId`,`testValueTypeId`,`sortOrder`) values (241,6,346,220);
insert  into `test_test_value_type`(`testTestValueTypeId`,`testId`,`testValueTypeId`,`sortOrder`) values (242,7,333,180);
insert  into `test_test_value_type`(`testTestValueTypeId`,`testId`,`testValueTypeId`,`sortOrder`) values (243,1,336,175);
insert  into `test_test_value_type`(`testTestValueTypeId`,`testId`,`testValueTypeId`,`sortOrder`) values (244,1,335,170);
insert  into `test_test_value_type`(`testTestValueTypeId`,`testId`,`testValueTypeId`,`sortOrder`) values (245,7,332,175);
insert  into `test_test_value_type`(`testTestValueTypeId`,`testId`,`testValueTypeId`,`sortOrder`) values (246,7,331,170);
insert  into `test_test_value_type`(`testTestValueTypeId`,`testId`,`testValueTypeId`,`sortOrder`) values (247,7,334,185);
insert  into `test_test_value_type`(`testTestValueTypeId`,`testId`,`testValueTypeId`,`sortOrder`) values (248,6,355,55);
insert  into `test_test_value_type`(`testTestValueTypeId`,`testId`,`testValueTypeId`,`sortOrder`) values (249,6,356,61);
insert  into `test_test_value_type`(`testTestValueTypeId`,`testId`,`testValueTypeId`,`sortOrder`) values (250,6,357,23);
insert  into `test_test_value_type`(`testTestValueTypeId`,`testId`,`testValueTypeId`,`sortOrder`) values (251,6,358,21);
insert  into `test_test_value_type`(`testTestValueTypeId`,`testId`,`testValueTypeId`,`sortOrder`) values (252,6,359,26);
insert  into `test_test_value_type`(`testTestValueTypeId`,`testId`,`testValueTypeId`,`sortOrder`) values (253,6,360,22);

/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;
/*!40014 SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS */;
/*!40111 SET SQL_NOTES=@OLD_SQL_NOTES */;
