USE cncappsdev;
GRANT SELECT ON `main_contacts` TO 'autorequest'@'%';
GRANT SELECT ON `callactivity` TO 'autorequest'@'%';
GRANT SELECT ON `custitem` TO 'autorequest'@'%';
GRANT SELECT ON `activitycategory` TO 'autorequest'@'%';
GRANT SELECT ON `problem` TO 'autorequest'@'%';
GRANT SELECT ON `auto_request_rootcause` TO 'autorequest'@'%';
GRANT SELECT (cns_manager, cns_consno, cns_name) ON `consultant` TO 'autorequest'@'%';
GRANT ALL PRIVILEGES ON `automated_request` TO 'autorequest'@'%' WITH GRANT OPTION;
GRANT SELECT ON `rootcause` TO 'autorequest'@'%';
GRANT SELECT ON `contact` TO 'autorequest'@'%';
GRANT SELECT ON `service_activity_search` TO 'autorequest'@'%';
GRANT SELECT ON `auto_request_activitycategory` TO 'autorequest'@'%';
GRANT SELECT ON `callacttype` TO 'autorequest'@'%';
GRANT SELECT ON `customer` TO 'autorequest'@'%';
GRANT SELECT ON `auto_request_contracts` TO 'autorequest'@'%';
GRANT SELECT ON `address` TO 'autorequest'@'%';
GRANT SELECT ON `item` TO 'autorequest'@'%';
GRANT SELECT ON `service_request_report` TO 'autorequest'@'%';
