UPDATE
custitem ci
JOIN renbroadband rb ON customerItemId = cui_custitemno
SET
	ci.`renewalDate` = rb.`renewalDate`,
	ci.`itemID` = rb.`itemID`,
	ci.`months` = rb.`months`,
	ci.`ordheadID` = rb.`ordheadID`,
	ci.`broadbandServiceType` = rb.`broadbandServiceType`,
	ci.`broadbandServiceTypeID` rb.`broadbandServiceTypeID`,
	ci.`adslPhone` = rb.`adslPhone`,
	ci.`fee` = rb.`fee`,
	ci.`macCode` = rb.`macCode`,
	ci.`batchNo` = rb.`batchNo`,
	ci.`reference` = rb.`reference`,
	ci.`defaultGateway` = rb.`defaultGateway`,
	ci.`networkAddress` = rb.`networkAddress`,
	ci.`subnetMask` = rb.`subnetMask`,
	ci.`routerIPAddress` = rb.`routerIPAddress`,
	ci.`userName` = rb.`userName`,
	ci.`password` = rb.`password`,
	ci.`etaDate` = rb.`etaDate`,
	ci.`installationDate` = rb.`installationDate`,
	ci.`costPerAnnum` = rb.`costPerAnnum`,
	ci.`salePricePerMonth` = rb.`salePricePerMonth`,
	ci.`costPricePerMonth` = rb.`costPricePerMonth`,
	ci.`ispID` = rb.`ispID`,
	ci.`requiresChangesFlag` = rb.`requiresChangesFlag`,
	ci.`dualBroadbandFlag` = rb.`dualBroadbandFlag`,
	ci.`dnsCompany` = rb.`dnsCompany`,
	ci.`ipCurrentNo` = rb.`ipCurrentNo`,
	ci.`mx` = rb.`mx`,
	ci.`secureServer` = rb.`secureServer`,
	ci.`vpns` = rb.`vpns`,
	ci.`owa` = rb.`owa`,
	ci.`oma` = rb.`oma`,
	ci.`remotePortal` = rb.`remotePortal`,
	ci.`smartHost` = rb.`smartHost`,
	ci.`preparationRecords` = rb.`preparationRecords`,
	ci.`assignedTo` = rb.`assignedTo`,
	ci.`initialSpeedTest` = rb.`initialSpeedTest`,
	ci.`preMigrationNotes` = rb.`preMigrationNotes`,
	ci.`postMigrationNotes` = rb.`postMigrationNotes`,
	ci.`docsUpdatedAndChecksCompleted` = rb.`docsUpdatedAndChecksCompleted`,
	ci.`invoicePeriodMonths` = rb.`invoicePeriodMonths`,
	ci.`totalInvoiceMonths` = rb.`totalInvoiceMonths`,
	ci.`declinedFlag` = rb.`declinedFlag`

