export const ADD_SITE = 'ADD_SITE';
export const UPDATE_SITE = 'UPDATE_SITE';
export const DELETE_SITE_REQUEST = 'DELETE_SITE_REQUEST';
export const DELETE_SITE_SUCCESS = 'DELETE_SITE_SUCCESS';
export const TOGGLE_VISIBILITY = 'TOGGLE_VISIBILITY';
export const CHANGE_INVOICE_SITE_NO = 'CHANGE_INVOICE_SITE_NO';
export const CHANGE_DELIVER_SITE_NO = 'CHANGE_DELIVER_SITE_NO';
export const FETCH_CONTACTS_REQUEST = 'FETCH_CONTACTS_REQUEST';
export const FETCH_CONTACTS_SUCCESS = 'FETCH_CONTACTS_SUCCESS';
export const FETCH_CONTACTS_FAILURE = 'FETCH_CONTACTS_FAILURE';
export const FETCH_SITES_REQUEST = 'FETCH_SITES_REQUEST';
export const FETCH_SITES_SUCCESS = 'FETCH_SITES_SUCCESS';
export const FETCH_SITES_FAILURE = 'FETCH_SITES_FAILURE';
export const FETCH_CUSTOMER_REQUEST = 'FETCH_CUSTOMER_REQUEST';
export const FETCH_CUSTOMER_SUCCESS = 'FETCH_CUSTOMER_SUCCESS';

export const FETCH_CUSTOMER_TYPES = 'FETCH_CUSTOMER_TYPES';
export const FETCH_CUSTOMER_TYPES_SUCCESS = 'FETCH_CUSTOMER_TYPES_SUCCESS';
export const FETCH_LEAD_STATUSES = 'FETCH_LEAD_STATUSES';
export const FETCH_LEAD_STATUSES_SUCCESS = 'FETCH_LEAD_STATUSES_SUCCESS';
export const FETCH_SECTORS = 'FETCH_SECTORS';
export const FETCH_SECTORS_SUCCESS = 'FETCH_SECTORS_SUCCESS';
export const FETCH_ACCOUNT_MANAGERS = 'FETCH_ACCOUNT_MANAGERS';
export const FETCH_ACCOUNT_MANAGERS_SUCCESS = 'FETCH_ACCOUNT_MANAGERS_SUCCESS';
export const FETCH_REVIEW_ENGINEERS = 'FETCH_REVIEW_ENGINEERS';
export const FETCH_REVIEW_ENGINEERS_SUCCESS = 'FETCH_REVIEW_ENGINEERS_SUCCESS';


export const ADD_CONTACT_TO_SITE = 'ADD_CONTACT_TO_SITE';
export const INITIALIZE_CUSTOMER = 'INITIALIZE_CUSTOMER';
export const REQUEST_SAVE_SITE = 'REQUEST_SAVE_SITE';
export const SAVE_SITE_SUCCESS = 'SAVE_SITE_SUCCESS';
export const SAVE_CUSTOMER_DATA_SUCCESS = 'SAVE_CUSTOMER_DATA_SUCCESS';