export const ADD_SITE = 'ADD_SITE';
export const UPDATE_SITE = 'UPDATE_SITE';
export const DELETE_SITE_REQUEST = 'DELETE_SITE_REQUEST';
export const DELETE_SITE_SUCCESS = 'DELETE_SITE_SUCCESS';
export const TOGGLE_VISIBILITY = 'TOGGLE_VISIBILITY';
export const CHANGE_INVOICE_SITE_NO = 'CHANGE_INVOICE_SITE_NO';
export const CHANGE_DELIVER_SITE_NO = 'CHANGE_DELIVER_SITE_NO';
export const FETCH_CONTACTS_REQUEST = 'FETCH_CONTACTS_REQUEST';
export const FETCH_CONTACTS_SUCCESS = 'FETCH_CONTACTS_SUCCESS';
export const FETCH_CONTACTS_FAILURE = 'FETCH_CONTACTS_FAILURE';
export const FETCH_SITES_REQUEST = 'FETCH_SITES_REQUEST';
export const FETCH_SITES_SUCCESS = 'FETCH_SITES_SUCCESS';
export const FETCH_SITES_FAILURE = 'FETCH_SITES_FAILURE';
export const FETCH_CUSTOMER_REQUEST = 'FETCH_CUSTOMER_REQUEST';
export const FETCH_CUSTOMER_SUCCESS = 'FETCH_CUSTOMER_SUCCESS';

export const FETCH_PROJECTS_REQUEST = 'FETCH_PROJECTS_REQUEST';
export const FETCH_PROJECTS_SUCCESS = 'FETCH_PROJECTS_SUCCESS';
export const FETCH_PROJECTS_FAILURE = 'FETCH_PROJECTS_FAILURE';

export const DELETE_PROJECT_REQUEST = 'DELETE_PROJECT_REQUEST';
export const DELETE_PROJECT_SUCCESS = 'DELETE_PROJECT_SUCCESS';
export const DELETE_PROJECT_FAILURE = 'DELETE_PROJECT_FAILURE';

export const FETCH_CUSTOMER_TYPES = 'FETCH_CUSTOMER_TYPES';
export const FETCH_CUSTOMER_TYPES_SUCCESS = 'FETCH_CUSTOMER_TYPES_SUCCESS';
export const FETCH_LEAD_STATUSES = 'FETCH_LEAD_STATUSES';
export const FETCH_LEAD_STATUSES_SUCCESS = 'FETCH_LEAD_STATUSES_SUCCESS';
export const FETCH_SECTORS = 'FETCH_SECTORS';
export const FETCH_SECTORS_SUCCESS = 'FETCH_SECTORS_SUCCESS';
export const FETCH_ACCOUNT_MANAGERS = 'FETCH_ACCOUNT_MANAGERS';
export const FETCH_ACCOUNT_MANAGERS_SUCCESS = 'FETCH_ACCOUNT_MANAGERS_SUCCESS';
export const FETCH_REVIEW_ENGINEERS = 'FETCH_REVIEW_ENGINEERS';
export const FETCH_REVIEW_ENGINEERS_SUCCESS = 'FETCH_REVIEW_ENGINEERS_SUCCESS';

export const UPDATE_CUSTOMER_VALUE = 'UPDATE_CUSTOMER_VALUE';
export const ADD_CONTACT_TO_SITE = 'ADD_CONTACT_TO_SITE';
export const INITIALIZE_CUSTOMER = 'INITIALIZE_CUSTOMER';
export const REQUEST_SAVE_SITE = 'REQUEST_SAVE_SITE';
export const SAVE_SITE_SUCCESS = 'SAVE_SITE_SUCCESS';
export const SAVE_CUSTOMER_DATA_SUCCESS = 'SAVE_CUSTOMER_DATA_SUCCESS';

export const REQUEST_UPDATE_CUSTOMER = "REQUEST_UPDATE_CUSTOMER";
export const REQUEST_UPDATE_CUSTOMER_SUCCESS = 'REQUEST_UPDATE_CUSTOMER_SUCCESS';
export const REQUEST_UPDATE_CUSTOMER_FAILED_OUT_OF_DATE = "REQUEST_UPDATE_CUSTOMER_FAILED_OUT_OF_DATE";
export const REQUEST_UPDATE_CUSTOMER_FAILED = 'REQUEST_UPDATE_CUSTOMER_FAILED';
export const DISMISS_ERROR = "DISMISS_ERROR";
export const ADD_ERROR = "ADD_ERROR"


export const NEW_PROJECT_FIELD_UPDATE = "NEW_PROJECT_FIELD_UPDATE";

export const HIDE_NEW_PROJECT_MODAL = "HIDE_NEW_PROJECT_MODAL";
export const SHOW_NEW_PROJECT_MODAL = "SHOW_NEW_PROJECT_MODAL";

export const REQUEST_ADD_PROJECT = "REQUEST_ADD_PROJECT";
export const REQUEST_ADD_PROJECT_SUCCESS = "REQUEST_ADD_PROJECT_SUCCESS";
export const REQUEST_ADD_PROJECT_FAILURE = "REQUEST_ADD_PROJECT_FAILURE";

export const FETCH_PORTAL_CUSTOMER_DOCUMENTS_REQUEST = "FETCH_PORTAL_CUSTOMER_DOCUMENTS_REQUEST";
export const FETCH_PORTAL_CUSTOMER_DOCUMENTS_SUCCESS = "FETCH_PORTAL_CUSTOMER_DOCUMENTS_SUCCESS";
export const FETCH_PORTAL_CUSTOMER_DOCUMENTS_FAILURE = "FETCH_PORTAL_CUSTOMER_DOCUMENTS_FAILURE";

export const DELETE_PORTAL_CUSTOMER_DOCUMENT_REQUEST = 'DELETE_PORTAL_CUSTOMER_DOCUMENT_REQUEST';
export const DELETE_PORTAL_CUSTOMER_DOCUMENT_SUCCESS = 'DELETE_PORTAL_CUSTOMER_DOCUMENT_SUCCESS';
export const DELETE_PORTAL_CUSTOMER_DOCUMENT_FAILURE = 'DELETE_PORTAL_CUSTOMER_DOCUMENT_FAILURE';

export const SHOW_NEW_PORTAL_CUSTOMER_DOCUMENT_MODAL = "SHOW_NEW_PORTAL_CUSTOMER_DOCUMENT_MODAL";
export const HIDE_NEW_PORTAL_CUSTOMER_DOCUMENT_MODAL = "HIDE_NEW_PORTAL_CUSTOMER_DOCUMENT_MODAL";
export const NEW_PORTAL_CUSTOMER_DOCUMENT_FIELD_UPDATE = "NEW_PORTAL_CUSTOMER_DOCUMENT_FIELD_UPDATE";
export const REQUEST_ADD_PORTAL_CUSTOMER_DOCUMENT = "REQUEST_ADD_PORTAL_CUSTOMER_DOCUMENT";
export const REQUEST_ADD_PORTAL_CUSTOMER_DOCUMENT_SUCCESS = "REQUEST_ADD_PORTAL_CUSTOMER_DOCUMENT_SUCCESS";
export const REQUEST_ADD_PORTAL_CUSTOMER_DOCUMENT_FAILURE = "REQUEST_ADD_PORTAL_CUSTOMER_DOCUMENT_FAILURE";


export const SHOW_NEW_SITE_MODAL = "SHOW_NEW_SITE_MODAL";
export const HIDE_NEW_SITE_MODAL = "HIDE_NEW_SITE_MODAL";
export const NEW_SITE_FIELD_UPDATE = "NEW_SITE_FIELD_UPDATE";
export const REQUEST_ADD_SITE = "REQUEST_ADD_SITE";
export const REQUEST_ADD_SITE_SUCCESS = "REQUEST_ADD_SITE_SUCCESS";
export const REQUEST_ADD_SITE_FAILURE = "REQUEST_ADD_SITE_FAILURE";